import type { FlowDefinition } from './types';

export const ownerLifecycle: FlowDefinition = {
  id: 'owner-lifecycle',
  label: 'Property Owner Journey',
  description: 'End-to-end lifecycle from signup to payout for property owners listing their timeshare weeks.',
  primaryRole: 'property_owner',
  roleEmoji: '✓',
  direction: 'TD',
  steps: [
    {
      id: 'signup',
      route: '/signup',
      label: 'Sign Up',
      component: 'Signup',
      nodeStyle: 'start',
      description: 'Owner registers with email/password or Google OAuth',
      tables: ['profiles', 'user_roles'],
    },
    {
      id: 'pending_approval',
      route: '/pending-approval',
      label: 'Await Approval',
      component: 'PendingApproval',
      nodeStyle: 'decision',
      description: 'Account pending RAV team review',
      tables: ['profiles'],
      branches: [
        { condition: 'Approved', targetStepId: 'welcome_onboarding', label: 'Approved' },
        { condition: 'Rejected', targetStepId: 'signup', label: 'Rejected', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'welcome_onboarding',
      route: '/welcome',
      label: 'Welcome Onboarding',
      component: 'WelcomePage',
      description: 'Post-approval gate: T&C reconfirm (Step 1) + role-specific getting-started CTAs for the owner (Step 2). Writes to terms_acceptance_log with post_approval_gate method.',
      tables: ['terms_acceptance_log', 'profiles'],
      branches: [
        { condition: 'Onboarding complete', targetStepId: 'request_owner_role', label: 'Continue to owner setup' },
      ],
    },
    {
      id: 'request_owner_role',
      route: '/owner-dashboard',
      label: 'Request Owner Role',
      component: 'RoleUpgradeDialog',
      description: 'User requests property_owner role upgrade',
      tables: ['role_upgrade_requests'],
    },
    {
      id: 'verify_identity',
      route: '/owner-dashboard',
      label: 'Upload Verification',
      component: 'OwnerVerification',
      tab: 'account',
      description: 'Owner uploads deed, certificate, or ID documents',
      tables: ['owner_verifications', 'verification_documents'],
      edgeFunctions: ['send-verification-notification'],
    },
    {
      id: 'referral_program',
      route: '/owner-dashboard',
      label: 'Referral Program',
      component: 'ReferralDashboard',
      tab: 'account',
      description: 'Owner generates a referral link, shares with other timeshare owners, and tracks signups + rewards',
      tables: ['referral_codes', 'referrals'],
    },
    {
      id: 'rav_tools',
      route: '/tools',
      label: 'RAV Tools Hub',
      component: 'RavTools',
      description: 'Central hub for all free tools: RAV SmartEarn calculator, SmartPrice, SmartCompare, SmartMatch, SmartBudget',
      branches: [
        { condition: 'Opens calculator', targetStepId: 'fee_calculator', label: 'RAV SmartEarn' },
      ],
    },
    {
      id: 'fee_calculator',
      route: '/calculator',
      label: 'RAV SmartEarn Calculator',
      component: 'MaintenanceFeeCalculator',
      description: 'Calculate breakeven point and projected savings vs. maintenance fees',
      branches: [
        { condition: 'Convinced to list', targetStepId: 'create_property', label: 'List my property' },
      ],
    },
    {
      id: 'create_property',
      route: '/list-property',
      label: 'Create Property & Listing',
      component: 'ListProperty',
      roles: ['property_owner'],
      description: 'Combined 3-step form: Property Details → Dates & Pricing → Review & Submit. Creates both property and listing in one flow. Draft auto-saves to localStorage; pending users can save drafts and publish after approval via OwnerDashboard banner.',
      tables: ['properties', 'listings'],
    },
    {
      id: 'check_listing_limit',
      route: '/owner-dashboard',
      label: 'Check Listing Limit',
      component: 'useCheckListingLimit',
      tab: 'my-listings',
      roles: ['property_owner'],
      nodeStyle: 'decision',
      description: 'System checks if owner is within their tier listing limit before creating a new listing.',
      tables: ['user_memberships', 'membership_tiers', 'listings'],
      branches: [
        { condition: 'Within limit', targetStepId: 'create_listing', label: 'Can create' },
        { condition: 'At limit', targetStepId: 'upgrade_plan', label: 'Upgrade needed', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'create_listing',
      route: '/owner-dashboard',
      label: 'Create Additional Listing',
      component: 'OwnerListings',
      tab: 'my-listings',
      roles: ['property_owner'],
      description: 'Create additional listings for existing properties. Set available dates, nightly rate pricing, cancellation policy.',
      tables: ['listings'],
    },
    {
      id: 'upgrade_plan',
      route: '/owner-dashboard',
      label: 'Upgrade Subscription',
      component: 'MembershipPlans',
      tab: 'account',
      roles: ['property_owner'],
      description: 'Owner upgrades to a higher tier via Stripe Checkout for more listings, commission discounts, and voice quota.',
      tables: ['user_memberships', 'membership_tiers'],
      edgeFunctions: ['create-subscription-checkout', 'stripe-webhook'],
      branches: [
        { condition: 'Upgraded', targetStepId: 'create_listing', label: 'Now within limit' },
      ],
    },
    {
      id: 'admin_review',
      route: '/admin',
      label: 'Admin Reviews Listing',
      component: 'AdminListings',
      roles: ['rav_admin', 'rav_staff'],
      nodeStyle: 'decision',
      description: 'RAV team approves or rejects the listing',
      tables: ['listings'],
      branches: [
        { condition: 'Approved', targetStepId: 'listing_active', label: 'Approved' },
        { condition: 'Rejected', targetStepId: 'create_listing', label: 'Needs changes', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'listing_active',
      route: '/rentals',
      label: 'Listing Live',
      component: 'Rentals',
      description: 'Listing visible to renters on the marketplace. Auto-matches open RAV Wishes.',
      tables: ['listings', 'notifications'],
      edgeFunctions: ['match-travel-requests'],
      branches: [
        { condition: 'Renter books directly', targetStepId: 'booking_confirmed', label: 'Renter pays' },
        { condition: 'Listing has flexible pricing', targetStepId: 'manage_bids', label: 'Flexible pricing' },
      ],
    },
    {
      id: 'manage_bids',
      route: '/owner-dashboard',
      label: 'Manage Offers & Date Requests',
      component: 'BidsManagerDialog',
      tab: 'my-listings',
      description: 'Owner reviews offers, accepts/rejects/counter-offers. Counter-offers trigger re-negotiation on this page. Accepting an offer does NOT create a booking — the renter must still pay at checkout.',
      tables: ['listing_bids'],
      branches: [
        { condition: 'Offer accepted, renter pays at checkout', targetStepId: 'booking_confirmed', label: 'Accepted → Renter pays' },
      ],
    },
    {
      id: 'booking_confirmed',
      route: '/owner-dashboard',
      label: 'Booking Confirmed',
      component: 'OwnerBookings',
      tab: 'bookings-earnings',
      description: 'Renter payment captured via Stripe, booking created and confirmed (verified by webhook + client). Appears in owner Bookings tab.',
      tables: ['bookings', 'booking_confirmations'],
      edgeFunctions: ['verify-booking-payment', 'stripe-webhook'],
      branches: [
        { condition: 'Proceed to owner confirmation', targetStepId: 'owner_confirmation', label: 'Confirm availability' },
        { condition: 'Owner cancels before confirmation', targetStepId: 'owner_cancellation', label: 'Cancel booking', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'owner_cancellation',
      route: '/owner-dashboard',
      label: 'Owner Cancellation',
      component: 'CancelBookingDialog',
      tab: 'bookings-earnings',
      roles: ['property_owner'],
      description: 'Owner-initiated cancellation with full refund to renter. Tracked in owner cancellation count (affects trust score).',
      edgeFunctions: ['process-cancellation', 'send-cancellation-email'],
      tables: ['cancellation_requests', 'bookings', 'owner_verifications'],
      nodeStyle: 'end',
    },
    {
      id: 'owner_confirmation',
      route: '/owner-dashboard',
      label: 'Owner Confirmation',
      component: 'OwnerConfirmationTimer',
      tab: 'bookings-earnings',
      roles: ['property_owner'],
      nodeStyle: 'decision',
      description: 'Owner confirms they can fulfill the booking within 60-min window (configurable). Can request up to 2 time extensions (30 min each).',
      tables: ['booking_confirmations'],
      edgeFunctions: ['process-deadline-reminders'],
      branches: [
        { condition: 'Owner confirms', targetStepId: 'submit_confirmation', label: 'Confirmed' },
        { condition: 'Owner declines or times out', targetStepId: 'owner_cancellation', label: 'Declined → refund', edgeStyle: 'dashed' },
      ],
    },
    {
      id: 'conversations_inbox',
      route: '/messages',
      label: 'Messages',
      component: 'Messages',
      description: 'Unified inbox — all conversations with travelers across bookings, bids, inquiries, and RAV Wishes',
      tables: ['conversations', 'conversation_messages'],
      branches: [
        { condition: 'Open thread', targetStepId: 'conversation_thread', label: 'View Thread' },
      ],
    },
    {
      id: 'conversation_thread',
      route: '/messages/:id',
      label: 'Conversation',
      component: 'Messages',
      description: 'Threaded view with messages and system events. Notification-dispatcher sends alerts for new messages.',
      tables: ['conversation_messages', 'conversation_events'],
      edgeFunctions: ['notification-dispatcher'],
    },
    {
      id: 'submit_confirmation',
      route: '/owner-dashboard',
      label: 'Submit Resort Confirmation',
      component: 'OwnerBookingConfirmations',
      tab: 'bookings-earnings',
      description: 'Owner provides resort confirmation number before deadline',
      tables: ['booking_confirmations'],
      edgeFunctions: ['send-booking-confirmation-reminder'],
    },
    {
      id: 'escrow_verified',
      route: '/admin',
      label: 'Escrow Verified',
      component: 'AdminEscrow',
      roles: ['rav_admin'],
      description: 'RAV verifies resort confirmation, releases escrow',
      tables: ['booking_confirmations'],
    },
    {
      id: 'payout',
      route: '/owner-dashboard',
      label: 'Payout Received',
      component: 'OwnerEarnings',
      tab: 'bookings-earnings',
      nodeStyle: 'end',
      description: 'Owner receives automated payout via Stripe Connect (or manual Zelle/bank) after checkout + 5 days',
      tables: ['bookings', 'profiles'],
      edgeFunctions: ['create-connect-account', 'create-stripe-payout'],
    },
  ],
};
